"""Investigation engine: provider → verifier routing (PRD 10, Phase 4).

The engine builds context, invokes the provider, validates the output through
Pydantic ``extra="forbid"`` models, and routes hypotheses through the Phase 3
``verify_case`` function.  Dry-run preview is called only after verifier PASS.

The model never calls the verifier.  The model returns data; the engine decides.

Hypothesis IDs are generated by ``hypothesis_id_for()`` from Phase 3 so proof
linkage stays deterministic.

Timeout enforcement on Windows uses a worker thread (``concurrent.futures``),
not ``signal.alarm``.
"""

from __future__ import annotations

import concurrent.futures
import time
from dataclasses import dataclass, replace
from typing import Any

from app.corrections.authority import classify_authority
from app.corrections.dry_run import DryRunResult, preview_correction
from app.domain.enums import (
    CaseStatus,
    HypothesisStatus,
    VerifierStatus,
)
from app.domain.records import AcceptedRecords
from app.investigator.budgets import InvestigationBudget
from app.investigator.prompt import build_investigation_context
from app.investigator.schemas import (
    ProviderResult,
)
from app.investigator.tools import ToolDispatcher
from app.reconciliation.detectors import CaseRecord
from app.verifier.engine import verify_case
from app.verifier.models import (
    StructuredHypothesis,
    VerifierResult,
    hypothesis_id_for,
)
from app.verifier.proof import ProofPackage, build_proof
from app.verifier.snapshot import EvidenceSnapshot, build_evidence_snapshot

# Cases eligible for investigation.
_INVESTIGABLE_STATUSES = frozenset({CaseStatus.UNRESOLVED, CaseStatus.VERIFICATION_FAILED})


@dataclass(frozen=True)
class CaseInvestigation:
    """One case's investigation result."""

    case: CaseRecord
    hypothesis: StructuredHypothesis | None
    verifier_result: VerifierResult | None
    proof: ProofPackage | None
    dry_run: DryRunResult | None
    provider_result: ProviderResult | None
    status: str  # outcome: "RESOLVED", "FAILED", "UNRESOLVED", "SKIPPED"
    failure_reason: str | None
    duration_ms: float


@dataclass(frozen=True)
class InvestigationResult:
    """All investigation outcomes for one run."""

    investigations: tuple[CaseInvestigation, ...]
    provider_id: str
    total_duration_ms: float

    @property
    def investigated_cases(self) -> tuple[CaseRecord, ...]:
        return tuple(item.case for item in self.investigations)

    def summary(self) -> dict[str, Any]:
        """Model-agnostic investigation summary for persistence.

        Contains tool_calls, retries, provider_id, per-case outcomes, and
        failure reasons.  No raw prompts or secrets.
        """
        status_counts: dict[str, int] = {}
        total_tool_calls = 0
        total_retries = 0
        per_case: list[dict[str, Any]] = []
        for item in self.investigations:
            status_counts[item.status] = status_counts.get(item.status, 0) + 1
            tool_calls = 0
            retries = 0
            if item.provider_result is not None:
                tool_calls = item.provider_result.tool_calls_used
                retries = item.provider_result.retries_used
            total_tool_calls += tool_calls
            total_retries += retries
            entry: dict[str, Any] = {
                "case_id": item.case.case_id,
                "category": item.case.category.value,
                "outcome": item.status,
                "tool_calls_used": tool_calls,
                "retries_used": retries,
                "duration_ms": round(item.duration_ms, 3),
            }
            if item.failure_reason:
                entry["failure_reason"] = item.failure_reason
            if item.hypothesis:
                entry["hypothesis_id"] = item.hypothesis.hypothesis_id
            if item.verifier_result:
                entry["verifier_status"] = item.verifier_result.status.value
            if item.proof:
                entry["proof_id"] = item.proof.proof_id
            if item.provider_result is not None and item.provider_result.trace:
                entry["trace"] = list(item.provider_result.trace)[:40]
            per_case.append(entry)

        return {
            "provider_id": self.provider_id,
            "status_counts": dict(sorted(status_counts.items())),
            "total_tool_calls": total_tool_calls,
            "total_retries": total_retries,
            "total_duration_ms": round(self.total_duration_ms, 3),
            "cases": per_case,
        }


def _collect_evidence_records(
    case: CaseRecord,
    snapshot: EvidenceSnapshot,
) -> dict[str, object]:
    """Gather the records cited by a case's evidence list."""
    records: dict[str, object] = {}
    for item in case.evidence:
        eid = f"{item.record_type}:{item.record_id}"
        record = snapshot.record(item.record_type, item.record_id)
        if record is not None:
            records[eid] = record
    return records


def _investigate_one_case(
    case: CaseRecord,
    provider: Any,  # InvestigatorProvider (avoid circular import)
    tools: ToolDispatcher,
    snapshot: EvidenceSnapshot,
    budget: InvestigationBudget,
    prior_hypotheses: tuple[StructuredHypothesis, ...],
    records: AcceptedRecords,
) -> CaseInvestigation:
    """Investigate one case: provider → validate → verify → dry-run."""
    started = time.perf_counter()

    # Build context
    evidence_records = _collect_evidence_records(case, snapshot)
    context = build_investigation_context(
        case,
        evidence_records,
        prior_hypotheses,
        budget.remaining_tool_calls,
    )

    # Call provider with timeout (worker thread for Windows compatibility)
    provider_result: ProviderResult | None = None
    failure_reason: str | None = None

    try:
        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(
                provider.investigate,
                case,
                tools,
                budget,
                context,
            )
            provider_result = future.result(timeout=budget.timeout_s)
    except concurrent.futures.TimeoutError:
        failure_reason = "provider timeout exceeded"
        duration_ms = (time.perf_counter() - started) * 1000.0
        return CaseInvestigation(
            case=replace(case, status=CaseStatus.INVESTIGATION_FAILED),
            hypothesis=None,
            verifier_result=None,
            proof=None,
            dry_run=None,
            provider_result=None,
            status="FAILED",
            failure_reason=failure_reason,
            duration_ms=duration_ms,
        )
    except Exception as exc:  # noqa: BLE001
        failure_reason = f"provider error: {type(exc).__name__}: {exc}"
        duration_ms = (time.perf_counter() - started) * 1000.0
        return CaseInvestigation(
            case=replace(case, status=CaseStatus.INVESTIGATION_FAILED),
            hypothesis=None,
            verifier_result=None,
            proof=None,
            dry_run=None,
            provider_result=None,
            status="FAILED",
            failure_reason=failure_reason,
            duration_ms=duration_ms,
        )

    # Provider returned unresolved — case stays/becomes UNRESOLVED
    if provider_result.unresolved is not None:
        duration_ms = (time.perf_counter() - started) * 1000.0
        return CaseInvestigation(
            case=replace(case, status=CaseStatus.UNRESOLVED),
            hypothesis=None,
            verifier_result=None,
            proof=None,
            dry_run=None,
            provider_result=provider_result,
            status="UNRESOLVED",
            failure_reason=None,
            duration_ms=duration_ms,
        )

    # Provider returned hypothesis — route through verifier
    assert provider_result.hypothesis is not None
    hyp_output = provider_result.hypothesis

    evidence_ids = hyp_output.evidence_ids
    hypothesis = StructuredHypothesis(
        hypothesis_id=hypothesis_id_for(
            case.case_id,
            hyp_output.category,
            evidence_ids,
        ),
        case_id=case.case_id,
        category=hyp_output.category,
        claim=hyp_output.claim,
        evidence_ids=evidence_ids,
    )

    # Run the Phase 3 verifier
    verifier_result = verify_case(case, hypothesis, snapshot)

    from datetime import UTC, datetime

    created_at_iso = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

    authority = classify_authority(
        verifier_result.status,
        verifier_result.proposed_delta_paise,
    )
    proof = build_proof(case, hypothesis, verifier_result, authority, created_at_iso)

    # Dry-run only on PASS
    dry_run: DryRunResult | None = None
    if verifier_result.status == VerifierStatus.PASS:
        updated_case = replace(
            case,
            status=authority.decision,
            proposed_delta_paise=verifier_result.proposed_delta_paise,
        )
        dry_run = preview_correction(updated_case, proof, snapshot, authority)
        proof = replace(proof, dry_run=dry_run)

        # Update hypothesis status
        hypothesis = replace(hypothesis, status=HypothesisStatus.SUPPORTED)

        duration_ms = (time.perf_counter() - started) * 1000.0
        return CaseInvestigation(
            case=updated_case,
            hypothesis=hypothesis,
            verifier_result=verifier_result,
            proof=proof,
            dry_run=dry_run,
            provider_result=provider_result,
            status="RESOLVED",
            failure_reason=None,
            duration_ms=duration_ms,
        )

    # FAIL or INCONCLUSIVE
    if verifier_result.status == VerifierStatus.FAIL:
        hypothesis = replace(
            hypothesis,
            status=HypothesisStatus.REJECTED,
            reason_codes=verifier_result.reason_codes,
        )
        updated_case = replace(case, status=CaseStatus.VERIFICATION_FAILED)
        outcome_status = "FAILED"
    else:
        # INCONCLUSIVE
        hypothesis = replace(
            hypothesis,
            status=HypothesisStatus.INCONCLUSIVE,
            reason_codes=verifier_result.reason_codes,
        )
        updated_case = replace(case, status=CaseStatus.UNRESOLVED)
        outcome_status = "UNRESOLVED"

    duration_ms = (time.perf_counter() - started) * 1000.0
    return CaseInvestigation(
        case=updated_case,
        hypothesis=hypothesis,
        verifier_result=verifier_result,
        proof=proof,
        dry_run=None,
        provider_result=provider_result,
        status=outcome_status,
        failure_reason=None,
        duration_ms=duration_ms,
    )


def investigate_cases(
    records: AcceptedRecords,
    cases: list[CaseRecord],
    provider: Any,  # InvestigatorProvider
    budget_config: InvestigationBudget | None = None,
    graph_json: dict[str, Any] | None = None,
) -> InvestigationResult:
    """Investigate eligible cases using the provider.

    Only ``UNRESOLVED`` and ``VERIFICATION_FAILED`` cases are investigated.
    Already-verified PASS cases are skipped.
    """
    if budget_config is None:
        budget_config = InvestigationBudget()

    snapshot = build_evidence_snapshot(records)

    # Build tool dispatcher
    case_map = {c.case_id: c for c in cases}
    tools = ToolDispatcher(
        snapshot=snapshot,
        records=records,
        cases=case_map,
        graph_json=graph_json or {},
    )

    investigations: list[CaseInvestigation] = []
    total_started = time.perf_counter()

    for case in cases:
        if case.status not in _INVESTIGABLE_STATUSES:
            # Skip — not eligible for investigation
            investigations.append(
                CaseInvestigation(
                    case=case,
                    hypothesis=None,
                    verifier_result=None,
                    proof=None,
                    dry_run=None,
                    provider_result=None,
                    status="SKIPPED",
                    failure_reason=None,
                    duration_ms=0.0,
                )
            )
            continue

        # Gather prior rejected hypotheses for this case (from prior
        # investigations in this run — not persisted across runs in Phase 4)
        prior_hypotheses: list[StructuredHypothesis] = []
        for prev in investigations:
            if (
                prev.hypothesis is not None
                and prev.hypothesis.case_id == case.case_id
                and prev.hypothesis.status
                in (
                    HypothesisStatus.REJECTED,
                    HypothesisStatus.INCONCLUSIVE,
                )
            ):
                prior_hypotheses.append(prev.hypothesis)

        result = _investigate_one_case(
            case=case,
            provider=provider,
            tools=tools,
            snapshot=snapshot,
            budget=budget_config,
            prior_hypotheses=tuple(prior_hypotheses),
            records=records,
        )
        investigations.append(result)

    total_ms = (time.perf_counter() - total_started) * 1000.0
    return InvestigationResult(
        investigations=tuple(investigations),
        provider_id=provider.provider_id,
        total_duration_ms=total_ms,
    )
